### ISSUE TITLE
trying to connect to Discourse forum with username & password

### ISSUE THREAD

**Issue by holtzermann17** [dickmao/nndiscourse#8]
I'm trying to connect to the Discourse site forum.openglobalmind.com (it's password protected, but I have a login).

I've tried:

```lisp
(custom-set-variables '(gnus-select-method
       (quote (nndiscourse "forum.openglobalmind.com" (nndiscourse-scheme "https")))))
```

Also, I had a look at the code for nndiscourse.el, and I don't see a place to enter my username and password, so I've done that in ~/.authinfo, `machine forum.openglobalmind.com login me@gmail.com password secret`

Config:

$ bundler --version
Bundler version 2.1.4

$ emacs --version
GNU Emacs 28.0.50

Here are my error messages:

```
Checking new news...
Reading active file from forum.openglobalmind.com via nndiscourse...
nndiscourse-rpc-request: JSON-RPC error condition: :code, -32099, :message, "Server application error: undefined method `[]' for nil:NilClass at /home/joe/.emacs.d/elpa/nndiscourse-20200829.1751/nndiscourse/vendor/bundle/ruby/2.7.0/bundler/gems/discourse_api-f7e79ed525bc/lib/discourse_api/api/categories.rb:31:in `categories'"
nndiscourse--incoming: last-id: nil, 
nndiscourse-request-scan: Took 2.759845809 seconds, with 0 gc runs taking 0.0 seconds
Checking new news...done
No news is good news
Warning: nndiscourse-rpc-request: JSON-RPC error condition: :code, -32099, :message, "Server application error: undefined method `[]' for nil:NilClass at /home/joe/.emacs.d/elpa/nndiscourse-20200829.1751/nndiscourse/vendor/bundle/ruby/2.7.0/bundler/gems/discourse_api-f7e79ed525bc/lib/discourse_api/api/categories.rb:31:in `categories'"
```

**Comment by dickmao** [comment]
nndiscourse is read-only (the read-only'ness includes not being able to login).

As of the time I wrote nndiscourse, the CSRF of Discourse essentially required a full-fledged browser.  My post https://meta.discourse.org/t/user-api-keys-specification/48536/33?u=dickmao
